/* Offline clinical reference data for search and suggestion only. It is not medical advice. */
const diseaseLibrary = [
    ["Type 1 diabetes", "diabetes, sugar, t1d", ["Insulin glargine", "Insulin lispro", "Glucagon"]],
    ["Type 2 diabetes", "diabetes, sugar, t2d", ["Metformin", "Glimepiride", "Sitagliptin", "Insulin glargine"]],
    ["Hypertension", "high blood pressure, bp, pressure", ["Amlodipine", "Losartan", "Telmisartan", "Atenolol"]],
    ["Asthma", "wheeze, breathing, inhaler", ["Salbutamol", "Budesonide", "Montelukast"]],
    ["COPD", "chronic obstructive pulmonary disease, breathing", ["Tiotropium", "Formoterol", "Salbutamol"]],
    ["Hypothyroidism", "underactive thyroid, thyroid", ["Levothyroxine"]],
    ["Hyperthyroidism", "overactive thyroid, thyroid", ["Carbimazole", "Propylthiouracil"]],
    ["Heart disease", "cardiac, coronary artery disease, cad", ["Aspirin", "Atorvastatin", "Bisoprolol"]],
    ["Arrhythmia", "irregular heartbeat, afib, atrial fibrillation", ["Amiodarone", "Apixaban", "Metoprolol"]],
    ["Chronic kidney disease", "ckd, kidney failure, renal", ["Furosemide", "Erythropoietin", "Sevelamer"]],
    ["Liver disease", "hepatic, cirrhosis, liver", ["Lactulose", "Ursodeoxycholic acid"]],
    ["Osteoarthritis", "arthritis, joint pain, oa", ["Paracetamol", "Naproxen", "Diclofenac"]],
    ["Rheumatoid arthritis", "arthritis, ra, joint inflammation", ["Methotrexate", "Hydroxychloroquine", "Adalimumab"]],
    ["Osteoporosis", "weak bones, bone density", ["Alendronate", "Calcium carbonate", "Vitamin D3"]],
    ["Depression", "low mood, major depressive disorder, mdd", ["Sertraline", "Fluoxetine", "Escitalopram"]],
    ["Anxiety disorder", "anxiety, panic, worry", ["Buspirone", "Sertraline", "Escitalopram"]],
    ["Bipolar disorder", "bipolar, mood swings", ["Lithium", "Valproate", "Quetiapine"]],
    ["Insomnia", "sleep problem, sleeplessness", ["Melatonin", "Zolpidem"]],
    ["Tuberculosis", "tb, pulmonary tb, infection", ["Isoniazid", "Rifampicin", "Pyrazinamide", "Ethambutol"]],
    ["HIV infection", "hiv, aids, human immunodeficiency virus", ["Tenofovir", "Lamivudine", "Dolutegravir"]],
    ["Hepatitis B", "hep b, liver infection", ["Tenofovir", "Entecavir"]],
    ["Hepatitis C", "hep c, liver infection", ["Sofosbuvir", "Velpatasvir"]],
    ["Malaria", "malarial fever, mosquito fever", ["Artemether", "Lumefantrine", "Chloroquine"]],
    ["Typhoid fever", "typhoid, enteric fever", ["Cefixime", "Azithromycin"]],
    ["Influenza", "flu, viral fever", ["Oseltamivir", "Paracetamol"]],
    ["COVID-19", "covid, coronavirus, sars cov 2", ["Paracetamol", "Nirmatrelvir"]],
    ["Pneumonia", "lung infection, chest infection", ["Amoxicillin", "Azithromycin", "Ceftriaxone"]],
    ["Urinary tract infection", "uti, urine infection, bladder infection", ["Nitrofurantoin", "Ciprofloxacin"]],
    ["Dengue fever", "dengue, mosquito fever", ["Paracetamol", "Oral rehydration salts"]],
    ["Epilepsy", "seizure, fits, convulsion", ["Levetiracetam", "Carbamazepine", "Lamotrigine"]],
    ["Migraine", "headache, migraine aura", ["Sumatriptan", "Topiramate", "Propranolol"]],
    ["Parkinson disease", "parkinson's, tremor, movement disorder", ["Levodopa", "Carbidopa", "Pramipexole"]],
    ["Alzheimer disease", "alzheimer's, dementia, memory loss", ["Donepezil", "Memantine"]],
    ["Multiple sclerosis", "ms, demyelinating disease", ["Interferon beta", "Fingolimod"]],
    ["Neuropathic pain", "nerve pain, neuropathy", ["Gabapentin", "Pregabalin", "Amitriptyline"]],
    ["Acid reflux", "gerd, heartburn, reflux", ["Omeprazole", "Pantoprazole", "Famotidine"]],
    ["Irritable bowel syndrome", "ibs, spastic colon, bowel", ["Mebeverine", "Loperamide"]],
    ["Peptic ulcer disease", "ulcer, stomach ulcer, gastric ulcer", ["Omeprazole", "Amoxicillin", "Clarithromycin"]],
    ["Constipation", "bowel movement, hard stool", ["Lactulose", "Bisacodyl", "Psyllium"]],
    ["Ulcerative colitis", "colitis, inflammatory bowel disease, ibd", ["Mesalazine", "Prednisolone"]],
    ["Crohn disease", "crohn's, inflammatory bowel disease, ibd", ["Budesonide", "Azathioprine"]],
    ["Celiac disease", "coeliac, gluten intolerance", ["Iron supplement", "Calcium carbonate"]],
    ["Allergic rhinitis", "hay fever, nasal allergy, allergy", ["Cetirizine", "Loratadine", "Fluticasone nasal"]],
    ["Food allergy", "allergy, anaphylaxis", ["Epinephrine", "Cetirizine"]],
    ["Atopic dermatitis", "eczema, skin allergy, dermatitis", ["Hydrocortisone", "Tacrolimus ointment"]],
    ["Psoriasis", "scaly skin, plaque psoriasis", ["Calcipotriol", "Methotrexate"]],
    ["Acne", "pimples, acne vulgaris", ["Benzoyl peroxide", "Adapalene", "Doxycycline"]],
    ["Fungal skin infection", "ringworm, tinea, fungal infection", ["Clotrimazole", "Terbinafine"]],
    ["Scabies", "itch mites, scabies rash", ["Permethrin"]],
    ["Anemia", "low hemoglobin, iron deficiency", ["Ferrous sulfate", "Folic acid", "Cyanocobalamin"]],
    ["Sickle cell disease", "sickle cell anemia, sickle", ["Hydroxyurea", "Folic acid"]],
    ["Thalassemia", "thalassemia, inherited anemia", ["Deferasirox", "Folic acid"]],
    ["Polycystic ovary syndrome", "pcos, pcod, irregular periods", ["Metformin", "Combined oral contraceptive"]],
    ["Endometriosis", "pelvic pain, endometriosis", ["Naproxen", "Leuprolide"]],
    ["Pregnancy-related care", "pregnancy, antenatal, prenatal", ["Folic acid", "Iron supplement", "Calcium carbonate"]],
    ["Menopause", "hot flushes, menopause", ["Estradiol", "Progesterone"]],
    ["Prostate enlargement", "bph, enlarged prostate", ["Tamsulosin", "Finasteride"]],
    ["Erectile dysfunction", "ed, impotence", ["Sildenafil", "Tadalafil"]],
    ["Gout", "uric acid, gout arthritis", ["Allopurinol", "Colchicine"]],
    ["Fibromyalgia", "chronic widespread pain", ["Duloxetine", "Pregabalin"]],
    ["Chronic fatigue syndrome", "me/cfs, fatigue", ["Vitamin B12", "Magnesium"]],
    ["Cancer general", "malignancy, tumor, oncology", ["Ondansetron", "Morphine"]],
    ["Breast cancer", "breast tumor, oncology", ["Tamoxifen", "Trastuzumab"]],
    ["Lung cancer", "lung tumor, oncology", ["Osimertinib", "Pembrolizumab"]],
    ["Prostate cancer", "prostate tumor, oncology", ["Leuprolide", "Bicalutamide"]],
    ["Colorectal cancer", "colon cancer, bowel cancer", ["Capecitabine", "Oxaliplatin"]],
    ["Glaucoma", "eye pressure, glaucoma", ["Timolol eye drops", "Latanoprost"]],
    ["Cataract", "cloudy lens, cataract", ["Artificial tears"]],
    ["Osteomyelitis", "bone infection", ["Vancomycin", "Ceftriaxone"]],
    ["Sepsis recovery", "sepsis, systemic infection", ["Piperacillin-tazobactam", "Vancomycin"]],
    ["Obesity", "weight management, overweight", ["Orlistat", "Semaglutide"]],
    ["Vitamin D deficiency", "low vitamin d, deficiency", ["Vitamin D3", "Cholecalciferol"]],
    ["Vitamin B12 deficiency", "low b12, deficiency", ["Cyanocobalamin", "Vitamin B12"]],
    ["Sleep apnea", "osa, snoring, sleep breathing", ["Modafinil"]],
    ["Hearing loss", "deafness, hearing", ["No routine medicine"]],
    ["Varicose veins", "veins, venous insufficiency", ["Diosmin"]],
    ["Deep vein thrombosis", "dvt, blood clot", ["Apixaban", "Heparin"]],
    ["Pulmonary embolism", "pe, lung clot", ["Apixaban", "Heparin"]],
    ["Chronic pain", "long term pain, pain management", ["Paracetamol", "Tramadol"]],
    ["Tension headache", "headache, stress headache", ["Paracetamol", "Ibuprofen"]],
    ["Common cold", "cold, runny nose, viral", ["Paracetamol", "Cetirizine"]]
].map(([name, synonyms, medicines]) => ({ name, synonyms, medicines }));

const medicineNames = [
    ["Metformin", "Glucophage"], ["Glimepiride", "Amaryl"], ["Sitagliptin", "Januvia"], ["Insulin glargine", "Lantus"], ["Insulin lispro", "Humalog"], ["Glucagon", "Baqsimi"], ["Acarbose", "Precose"], ["Pioglitazone", "Actos"], ["Empagliflozin", "Jardiance"], ["Dapagliflozin", "Forxiga"],
    ["Amlodipine", "Norvasc"], ["Losartan", "Cozaar"], ["Telmisartan", "Micardis"], ["Atenolol", "Tenormin"], ["Ramipril", "Altace"], ["Enalapril", "Vasotec"], ["Lisinopril", "Zestril"], ["Valsartan", "Diovan"], ["Hydrochlorothiazide", "Microzide"], ["Furosemide", "Lasix"], ["Bisoprolol", "Zebeta"], ["Diltiazem", "Cardizem"], ["Clonidine", "Catapres"], ["Methyldopa", "Aldomet"], ["Nifedipine", "Adalat"],
    ["Salbutamol", "Ventolin"], ["Budesonide", "Pulmicort"], ["Montelukast", "Singulair"], ["Tiotropium", "Spiriva"], ["Formoterol", "Foradil"], ["Fluticasone inhaler", "Flovent"], ["Salmeterol", "Serevent"], ["Ipratropium", "Atrovent"], ["Theophylline", "Theo-24"], ["Prednisolone", "Orapred"],
    ["Levothyroxine", "Synthroid"], ["Carbimazole", "Neo-Mercazole"], ["Propylthiouracil", "PTU"], ["Aspirin", "Bayer"], ["Atorvastatin", "Lipitor"], ["Amiodarone", "Cordarone"], ["Apixaban", "Eliquis"], ["Metoprolol", "Lopressor"], ["Dabigatran", "Pradaxa"], ["Warfarin", "Coumadin"], ["Clopidogrel", "Plavix"], ["Rosuvastatin", "Crestor"], ["Pravastatin", "Pravachol"], ["Nitroglycerin", "Nitrostat"],
    ["Erythropoietin", "Epogen"], ["Sevelamer", "Renvela"], ["Ursodeoxycholic acid", "Ursofalk"], ["Lactulose", "Duphalac"], ["Paracetamol", "Tylenol"], ["Naproxen", "Aleve"], ["Diclofenac", "Voltaren"], ["Methotrexate", "Trexall"], ["Hydroxychloroquine", "Plaquenil"], ["Adalimumab", "Humira"], ["Alendronate", "Fosamax"], ["Calcium carbonate", "Tums"], ["Vitamin D3", "Cholecalciferol"], ["Sertraline", "Zoloft"], ["Fluoxetine", "Prozac"], ["Escitalopram", "Lexapro"], ["Buspirone", "Buspar"], ["Lithium", "Lithobid"], ["Valproate", "Depakote"], ["Quetiapine", "Seroquel"], ["Melatonin", "Circadin"], ["Zolpidem", "Ambien"],
    ["Isoniazid", "Nydrazid"], ["Rifampicin", "Rifadin"], ["Pyrazinamide", "Tebrazid"], ["Ethambutol", "Myambutol"], ["Tenofovir", "Viread"], ["Lamivudine", "Epivir"], ["Dolutegravir", "Tivicay"], ["Entecavir", "Baraclude"], ["Sofosbuvir", "Sovaldi"], ["Velpatasvir", "Epclusa"], ["Artemether", "Artemotil"], ["Lumefantrine", "Coartem"], ["Chloroquine", "Aralen"], ["Cefixime", "Suprax"], ["Azithromycin", "Zithromax"], ["Oseltamivir", "Tamiflu"], ["Nirmatrelvir", "Paxlovid"], ["Amoxicillin", "Amoxil"], ["Ceftriaxone", "Rocephin"], ["Nitrofurantoin", "Macrobid"], ["Ciprofloxacin", "Cipro"], ["Oral rehydration salts", "ORS"], ["Levetiracetam", "Keppra"], ["Carbamazepine", "Tegretol"], ["Lamotrigine", "Lamictal"], ["Sumatriptan", "Imitrex"], ["Topiramate", "Topamax"], ["Propranolol", "Inderal"], ["Levodopa", "Dopar"], ["Carbidopa", "Lodosyn"], ["Pramipexole", "Mirapex"], ["Donepezil", "Aricept"], ["Memantine", "Namenda"], ["Interferon beta", "Avonex"], ["Fingolimod", "Gilenya"], ["Gabapentin", "Neurontin"], ["Pregabalin", "Lyrica"], ["Amitriptyline", "Elavil"], ["Omeprazole", "Prilosec"], ["Pantoprazole", "Protonix"], ["Famotidine", "Pepcid"], ["Mebeverine", "Colofac"], ["Loperamide", "Imodium"], ["Bisacodyl", "Dulcolax"], ["Psyllium", "Metamucil"], ["Mesalazine", "Asacol"], ["Azathioprine", "Imuran"], ["Iron supplement", "Ferrous sulfate"], ["Cefixime", "Cefspan"], ["Cetirizine", "Zyrtec"], ["Loratadine", "Claritin"], ["Fluticasone nasal", "Flonase"], ["Epinephrine", "EpiPen"], ["Hydrocortisone", "Cortaid"], ["Tacrolimus ointment", "Protopic"], ["Calcipotriol", "Dovonex"], ["Benzoyl peroxide", "Benzac"], ["Adapalene", "Differin"], ["Doxycycline", "Vibramycin"], ["Clotrimazole", "Canesten"], ["Terbinafine", "Lamisil"], ["Permethrin", "Elimite"], ["Ferrous sulfate", "Fero-Grad"], ["Folic acid", "Folvite"], ["Cyanocobalamin", "Nascobal"], ["Hydroxyurea", "Hydrea"], ["Deferasirox", "Exjade"], ["Combined oral contraceptive", "Yaz"], ["Leuprolide", "Lupron"], ["Estradiol", "Estrace"], ["Progesterone", "Prometrium"], ["Tamsulosin", "Flomax"], ["Finasteride", "Proscar"], ["Sildenafil", "Viagra"], ["Tadalafil", "Cialis"], ["Allopurinol", "Zyloprim"], ["Colchicine", "Colcrys"], ["Duloxetine", "Cymbalta"], ["Magnesium", "Mag-Ox"], ["Ondansetron", "Zofran"], ["Morphine", "MS Contin"], ["Tamoxifen", "Nolvadex"], ["Trastuzumab", "Herceptin"], ["Osimertinib", "Tagrisso"], ["Pembrolizumab", "Keytruda"], ["Bicalutamide", "Casodex"], ["Capecitabine", "Xeloda"], ["Oxaliplatin", "Eloxatin"], ["Timolol eye drops", "Timoptic"], ["Latanoprost", "Xalatan"], ["Artificial tears", "Refresh"], ["Vancomycin", "Vancocin"], ["Piperacillin-tazobactam", "Zosyn"], ["Orlistat", "Xenical"], ["Semaglutide", "Ozempic"], ["Vitamin B12", "Cobalamin"], ["Modafinil", "Provigil"], ["Diosmin", "Daflon"], ["Heparin", "Hep-Lock"], ["Tramadol", "Ultram"], ["No routine medicine", "N/A"]
];

const additionalMedicineNames = [
    ["Ranitidine", "Zantac"], ["Domperidone", "Motilium"], ["Sucralfate", "Carafate"], ["Mupirocin", "Bactroban"], ["Ketoconazole", "Nizoral"], ["Acyclovir", "Zovirax"], ["Valacyclovir", "Valtrex"], ["Amphotericin B", "Fungizone"], ["Clindamycin", "Cleocin"], ["Metronidazole", "Flagyl"], ["Co-trimoxazole", "Bactrim"], ["Meropenem", "Merrem"], ["Linezolid", "Zyvox"], ["Rivaroxaban", "Xarelto"], ["Enoxaparin", "Lovenox"], ["Spironolactone", "Aldactone"], ["Digoxin", "Lanoxin"], ["Ivabradine", "Corlanor"], ["Sacubitril-valsartan", "Entresto"], ["Gliclazide", "Diamicron"], ["Linagliptin", "Trajenta"], ["Liraglutide", "Victoza"], ["Dexamethasone", "Decadron"], ["Methylprednisolone", "Medrol"], ["Cyclobenzaprine", "Flexeril"], ["Baclofen", "Lioresal"], ["Rizatriptan", "Maxalt"], ["Clonazepam", "Klonopin"], ["Alprazolam", "Xanax"], ["Venlafaxine", "Effexor"], ["Bupropion", "Wellbutrin"], ["Mirtazapine", "Remeron"], ["Risperidone", "Risperdal"], ["Olanzapine", "Zyprexa"], ["Aripiprazole", "Abilify"], ["Ropinirole", "Requip"], ["Rasagiline", "Azilect"], ["Rivastigmine", "Exelon"], ["Sodium valproate", "Epilim"], ["Ethosuximide", "Zarontin"]
];

const medicineLibrary = Object.fromEntries([...medicineNames, ...additionalMedicineNames].map(([name, brandNames]) => [name, { dosage: "As prescribed", frequency: 1, brandNames }]));
const healthLibrary = diseaseLibrary.map((disease) => ({ kind: "Disease", name: disease.name, terms: `${disease.name} ${disease.synonyms}`, text: `General information about ${disease.name}.`, advice: "Discuss diagnosis, treatment, and monitoring with a qualified clinician." }));
